local M = {}

--- Get the name of the current project directory
---@return string
function M.get_project_directory()
  return vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
end

--- Helper function to recursively scan directories
--- Recursively scan a directory and accumulate all subdirectories in the provided accumulator table, while excluding specified directories.
---@param path string
---@param acc string[]
local function scan(path, acc, excludes)
  for name, type in vim.fs.dir(path) do
    if not (excludes and vim.tbl_contains(excludes, name)) then
      local full = path .. "/" .. name
      if type == "directory" then
        table.insert(acc, full)
        scan(full, acc)
      end
    end
  end
end

--- Recursively get all directories under a given path while excluding specified directories.
---@param base_path string The base path to start scanning from
---@param excludes string[]? List of directory names to exclude from the results
---@return string[]
function M.get_all_directories(base_path, excludes)
  local dirs = {}
  scan(base_path, dirs, excludes)
  return dirs
end

--- Prompt the user for a title and return a slugified version of it and the original title.
--- The slug is generated by converting the title to lowercase, removing non-alphanumeric characters (except spaces), and replacing spaces with hyphens.
---@return string|nil
---@return string|nil
function M.prompt_title()
  local title = vim.fn.input("Axiom Title: ")
  if title == "" then return nil end
  return title, title:lower():gsub("[^a-z0-9 ]", ""):gsub("%s+", "-")
end

return M
